namespace ProtocolsIndexer.Models;

public record RagQueryResult(
    string                 Answer,
    string                 RetrievedContext,
    string                 SystemInstructions,
    int                    ChunksRetrieved,
    string                 OperationName,
    string                 ProviderName,
    string                 ServerAddress,
    int                    ServerPort,
    string                 ConversationId,
    string                 Model,
    string                 FinishReason,
    long                   LatencyMs,
    int                    InputTokens,
    int                    OutputTokens,
    int                    TotalTokens,
    float?                 Temperature,
    int?                   MaxOutputTokens,
    float?                 TopP,
    int?                   TopK,
    float?                 FrequencyPenalty,
    float?                 PresencePenalty,
    long?                  Seed,
    string?                ResponseFormat,
    IReadOnlyList<string>? StopSequences);
